---
- hosts: all
  become: yes
  vars:
    userFile: /home/vagrant/list
  tasks:
    - name: create file
      file:
        path: "{{ userFile }}"
        state: touch
    - name: list users
      lineinfile:
        path: "{{ userFile }}"
        line: "{{ item }}"
      with_items:
        - "{{ staff }}"
        - "{{ faculty }}"
        - "{{ other }}"
